---
apiVersion: apps/v1
kind: Deployment                 # Type of Kubernetes resource
metadata:
  name: go-coding-challenge           # Name of the Kubernetes resource
spec:
  replicas: 3                    # Number of pods to run at any given time
  selector:
    matchLabels:
      app: go-coding-challenge        # This deployment applies to any Pods matching the specified label
  template:                      # This deployment will create a set of pods using the configurations in this template
    metadata:
      labels:                    # The labels that will be applied to all of the pods in this deployment
        app: go-coding-challenge
    spec:                        # Spec for the container which will run in the Pod
      containers:
        - name: go-coding-challenge
          image: vleilamitchell/go-coding-challenge:0.5.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 10000  # Should match the port number that the Go application listens on
          livenessProbe:           # To check the health of the Pod
            httpGet:
              path: /health
              port: 10000
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
          readinessProbe:          # To check if the Pod is ready to serve traffic or not
            httpGet:
              path: /readiness
              port: 10000
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 1
